<?php

namespace RP\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimeRepository extends EntityRepository
{
}
