<?php

namespace RP\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FollowSerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowSerieRepository extends EntityRepository
{
}
